import { Mistral } from '@mistralai/mistralai';

export const ANALYZER_MODEL = process.env.MISTRAL_ANALYSIS_MODEL || 'mistral-large-latest';

const MAX_CHARS = 6000;

const SYSTEM_PROMPT = `You are a Forensic Content Analyst specializing in detecting AI-generated text. Your task is to analyze the provided text and determine the probability it was generated by an AI language model.

Respond ONLY with a valid JSON object — no prose, no markdown fences — in this exact format:
{
  "aiScore": <integer 0-100>,
  "reasoning": "<2-4 sentences explaining your assessment>",
  "roboticPhrases": ["<phrase1>", "<phrase2>"]
}

Scoring guide:
- 0-20:  Almost certainly human-written (personal voice, imperfections, spontaneity)
- 21-45: Probably human, with occasional AI-like patterns
- 46-70: Mixed signals — could be lightly AI-assisted or heavily edited
- 71-89: Likely AI-generated
- 90-100: Almost certainly AI-generated

Key signals to detect:
- Unnaturally perfect grammar with no authentic voice
- Repetitive transition phrases ("Furthermore", "Moreover", "In conclusion", "It is worth noting")
- Overly balanced, non-committal argument structure
- Formulaic paragraph pattern: claim → evidence → conclusion, repeated
- Precise but soulless descriptive language with no cultural specificity
- Lack of humor, contractions, or human error
- Suspiciously complete coverage of a topic with no clear perspective`;

/**
 * Safely extracts a string from Mistral's message content (string or content-block array).
 */
function contentToString(content) {
  if (typeof content === 'string') return content;
  if (!content) return '';
  if (Array.isArray(content)) {
    return content
      .map((c) => (typeof c === 'string' ? c : c?.text ?? ''))
      .join('');
  }
  return String(content);
}

/**
 * Finds phrase positions in source text for highlight spans.
 * @param {string} text Full source text
 * @param {string[]} phrases AI-like phrases returned by model
 * @returns {{ start: number, end: number, label: string }[]}
 */
function buildHighlights(text, phrases) {
  const highlights = [];
  for (const phrase of phrases) {
    if (!phrase || typeof phrase !== 'string') continue;
    const idx = text.indexOf(phrase);
    if (idx !== -1) {
      highlights.push({ start: idx, end: idx + phrase.length, label: 'AI-like phrasing' });
    }
  }
  return highlights;
}

/**
 * Analyzes text using Mistral's Forensic Specialist prompt.
 * Returns fields compatible with the existing UI record shape.
 *
 * @param {string} text
 * @returns {Promise<{
 *   score: number,        // 0-100, higher = more human (UI backwards compat)
 *   aiScore: number,      // 0-100, higher = more AI (new field)
 *   explanation: string,
 *   highlights: Array,
 *   realPercent: number,
 *   fakePercent: number,
 *   roboticPhrases: string[],
 * }>}
 */
export async function analyzeWithMistral(text) {
  const apiKey = process.env.MISTRAL_API_KEY?.trim();
  if (!apiKey) {
    throw new Error('MISTRAL_API_KEY is not configured');
  }

  const body = (text || '').trim();
  if (!body) {
    throw new Error('No text to analyze');
  }

  const snippet = body.length > MAX_CHARS ? body.slice(0, MAX_CHARS) : body;
  const truncated = body.length > MAX_CHARS;

  const client = new Mistral({ apiKey });

  let res;
  try {
    res = await client.chat.complete({
      model: ANALYZER_MODEL,
      messages: [
        { role: 'system', content: SYSTEM_PROMPT },
        { role: 'user', content: `Analyze the following text:\n\n${snippet}` },
      ],
      temperature: 0.1,
      responseFormat: { type: 'json_object' },
    });
  } catch (e) {
    const msg = e?.message || String(e);
    if (msg.includes('401') || msg.toLowerCase().includes('unauthorized')) {
      throw new Error('Mistral API key is invalid or missing.');
    }
    if (msg.includes('429')) {
      throw new Error('Mistral rate limit reached. Please try again shortly.');
    }
    throw new Error(`Mistral analysis failed: ${msg}`);
  }

  const raw = contentToString(res?.choices?.[0]?.message?.content);

  let parsed;
  try {
    parsed = JSON.parse(raw.trim());
  } catch {
    throw new Error('Mistral returned an invalid JSON response for analysis.');
  }

  const aiScore = Math.max(0, Math.min(100, Math.round(Number(parsed.aiScore) || 0)));
  const reasoning = String(parsed.reasoning || 'Analysis complete.');
  const roboticPhrases = Array.isArray(parsed.roboticPhrases)
    ? parsed.roboticPhrases.filter((p) => typeof p === 'string' && p.length > 0)
    : [];

  const suffix = truncated ? ` (Analysis used the first ${MAX_CHARS} characters.)` : '';
  const explanation = reasoning + suffix;

  const highlights = buildHighlights(body, roboticPhrases);

  if (highlights.length === 0 && aiScore >= 70) {
    highlights.push({ start: 0, end: body.length, label: 'Linguistic Anomalies Detected' });
  }

  const score = 100 - aiScore;
  const realPercent = score;
  const fakePercent = aiScore;

  return {
    score,
    aiScore,
    explanation,
    highlights,
    realPercent,
    fakePercent,
    roboticPhrases,
  };
}
